### ISSUE TITLE
Request for Final year project 

### ISSUE THREAD

**Issue by malikazhar074** [quantum-visualizations/qmsolve#31]
How are you? I have seen your videos on YouTube. Physics simulation videos are very beautiful and I am a final semester student of bachelor degree in physics and my final year project is also on physics simulation. It didn't work. Can you help me? Make me project at reasonable price.I share more details of the project with you if you want to make it.

**Comment by rafael-fuente** [comment]
Hi, I can collaborate on research projects but I do not make bachelor's thesis

**Comment by malikazhar074** [comment]
The simulations with time dependent Schrodinger equation  in your repositories are not running. You have updated a lot of things in it. Please tell me the solution. Explain in detail what needs to be done.

**Comment by malikazhar074** [comment]
Ok kindly share your what's app number or other contact number I will
discuss you about my project kindly response it I will be very thankful to
you.

The simulations with time dependent Schrodinger equation in your
repositories are not running. You have updated a lot of things in it.
Please tell me the solution. Explain in detail what needs to be done.
